export const CHAT = {
  pt: {
    "Posso contratar um diretor por R$20k?": "**Análise: Contratar Diretor por R$20k/mês**\n\nCom base nos seus dados financeiros:\n\n📊 **Situação atual:**\n• Receita: $120k/mês\n• Despesas: $85k/mês\n• Margem líquida: $35k (29%)\n• Runway: 87 dias\n\n⚠️ **Impacto da contratação:**\nSalário de $20k = 57% da sua margem atual. Sua margem cairia de 29% → ~12% e o runway despencaria para ~38 dias.\n\n❌ **Recomendação: Não agora.**\n\nAntes de contratar, sugiro:\n1. Crescer receita para $150k/mês (+25%)\n2. Ou cortar $12k em outras despesas\n3. Considerar contrato com variável (fixo $10k + bônus)\n\nRevisitar em 90 dias após estabilizar o runway.",
    "Quando vou atingir o break-even?": "**Análise de Break-even**\n\n🎉 Boa notícia: você já passou do break-even!\n\n📊 **Situação:**\n• Break-even: $82.000/mês\n• Receita atual: $120.000/mês\n• Margem de segurança: $38.000 (46%)\n\n📈 **Projeção com crescimento de 8%/mês:**\n• Abr: $129.600 → segurança de $47.600\n• Mai: $139.968 → segurança de $57.968\n• Jun: $151.165 → segurança de $69.165",
    "Qual meu risco financeiro atual?": "**Relatório de Risco — Março 2025**\n\n🔴 **Risco Geral: MÉDIO-ALTO (Score 42/100)**\n\n**Riscos por prioridade:**\n\n🔴 Crítico — Concentração de clientes\n→ 42% da receita em 1 cliente. Perda potencial: $50.400/mês.\n\n🟡 Moderado — Runway curto\n→ 87 dias (ideal: 180+). Revisar custos até maio.\n\n🟢 Baixo — Margem e crescimento\n→ 29% margem e +8%/mês são sólidos.",
    "Como melhorar minha margem?": "**Estratégias para Margem 29% → 35%+**\n\n💰 **Alavanca 1 — Aumentar receita:**\n• Reajuste de 3-5% nos preços → +$3.600/mês\n• Upsell para clientes atuais → menor custo de venda\n• Meta: $140k/mês em 60 dias\n\n✂️ **Alavanca 2 — Reduzir custos:**\n• Marketing: subiu 8% — revisar ROI de campanhas\n• Fornecedores: renegociar contratos (-5-10%)\n• Economia estimada: $8-12k/mês\n\n📊 **Resultado:** Margem de 36-38% em 90 dias.",
  },
  en: {
    "Can I hire a director for $20k?": "**Analysis: Hiring a Director for $20k/month**\n\n📊 **Current situation:**\n• Revenue: $120k/month · Expenses: $85k/month\n• Net margin: $35k (29%) · Runway: 87 days\n\n⚠️ $20k = 57% of current margin. Margin drops 29%→12%, runway ~38 days.\n\n❌ **Not now.** Grow to $150k/month first, or cut $12k elsewhere.",
    "When will I reach break-even?": "**Break-even Analysis**\n\n🎉 You've already passed break-even!\n\n• Break-even: $82,000/month · Revenue: $120,000/month · Safety margin: $38,000 (46%)",
    "What is my financial risk?": "**Risk Report — March 2025**\n\n🔴 Overall Risk: MEDIUM-HIGH (Score 42/100)\n\n🔴 Critical — Customer concentration: 42% in 1 client\n🟡 Moderate — Short runway: 87 days (ideal 180+)\n🟢 Low — Margin & growth: 29% and +8%/month",
    "How can I improve my margin?": "**Margin Improvement: 29% → 35%+**\n\n💰 Lever 1 — Raise revenue: 3-5% price increase → +$3,600/month\n✂️ Lever 2 — Cut costs: Marketing ROI review · Supplier renegotiation (-5-10%)\n📊 Result: 36-38% margin in 90 days.",
  },
  es: {
    "¿Puedo contratar un director por $20k?": "**Análisis: Contratar Director por $20k/mes**\n\n📊 Ingresos: $120k · Gastos: $85k · Margen: 29% · Runway: 87 días\n\n⚠️ $20k = 57% del margen. Bajaría a ~12%, runway ~38 días.\n\n❌ No ahora. Primero crecer a $150k/mes.",
    "¿Cuándo alcanzaré el break-even?": "**Análisis de Break-even**\n\n🎉 ¡Ya superó el break-even!\n\n• Break-even: $82.000/mes · Ingresos: $120.000/mes · Margen: $38.000 (46%)",
    "¿Cuál es mi riesgo financiero?": "**Informe de Riesgo — Marzo 2025**\n\n🔴 Riesgo: MEDIO-ALTO (Score 42/100)\n\n🔴 Concentración: 42% en 1 cliente\n🟡 Runway: 87 días (ideal 180+)\n🟢 Margen y crecimiento: sólidos",
    "¿Cómo mejorar mi margen?": "**Margen 29% → 35%+**\n\n💰 Aumento de precios 3-5% → +$3.600/mes\n✂️ Revisar ROI de marketing · Renegociar proveedores (-5-10%)\n📊 Resultado: 36-38% de margen en 90 días.",
  },
};

export const AI_ANALYSIS = {
  cashflow: "**Análise do Fluxo de Caixa — Março 2025**\n\n✅ **Sinal positivo:** Receita ($120k) supera despesas ($85k) em todos os meses analisados.\n\n📈 **Tendência:** Receita crescendo +22% em 6 meses. Despesas crescendo mais devagar (+20%), o que é saudável.\n\n⚠️ **Atenção:** Margem operacional ficou em $35k em março (29%) — acima da média do setor.\n\n💡 **Recomendação:** Mantenha crescimento de receita acima de 5%/mês para evitar que despesas fixas corroam a margem.",
  forecast: "**Análise da Previsão de 90 Dias**\n\n✅ **Positivo:** Todos os meses projetados ficam acima do break-even ($82k), com margem de segurança média de $47k.\n\n📊 **Abril** é o mês mais forte (proj. $125k, +$43k acima do equilíbrio).\n\n⚠️ **Junho** mostra leve queda vs Maio — monitorar sazonalidade.\n\n💡 **Ação:** Considere antecipar investimentos estratégicos em Abril quando o caixa estará mais folgado.",
  concentration: "**Análise de Concentração de Clientes**\n\n🔴 **Risco crítico:** Acme Corp representa 42% da receita. O padrão de segurança é máximo 25% por cliente.\n\n📊 **Distribuição atual:**\n• Acme Corp: 42% — RISCO ALTO\n• TechStart: 28% — moderado\n• BuildCo: 18% — ok\n• Outros: 12% — ok\n\n💡 **Ação imediata:** Prospectar pelo menos 2 novos clientes para diluir a concentração abaixo de 30% em 6 meses.",
  revenue: "**Análise da Receita Histórica**\n\n✅ **Excelente crescimento:** +36% em 7 meses (Set→Mar), média de +4,4%/mês.\n\n📈 **Melhor mês:** Março ($120k). Único mês de queda: Janeiro ($103k, -8% vs Dez) — típico de sazonalidade pós-festas.\n\n🎯 **Projeção:** Mantendo a taxa atual, você atingirá $140k/mês até Junho.\n\n💡 **Oportunidade:** A queda de Janeiro pode ser mitigada com campanhas antecipadas em Dezembro.",
  expenses: "**Análise de Despesas por Categoria**\n\n📊 **Maiores despesas:**\n• Folha de Pagamento: $48k (56% do total) — dentro do padrão\n• Marketing: $12k (+8% no mês) — merece atenção ao ROI\n• Operações: $10k (-2%) — tendência positiva\n\n⚠️ **Alerta:** Marketing cresceu 8% sem análise de retorno documentada.\n\n✅ **Positivo:** Despesas totais caíram 3% vs mês anterior.",
  exphistory: "**Análise Histórica de Despesas**\n\n📈 **Tendência geral:** Despesas cresceram 20% em 6 meses, acompanhando o crescimento da receita.\n\n⚠️ **Pico em Dezembro:** $80k — provavelmente 13º salário e despesas de fim de ano.\n\n✅ **Março estável:** $85k, crescimento controlado de 3,7% vs Fevereiro.",
  pierevenuebycat: "**Análise de Receita por Cliente**\n\n🔴 Acme Corp está em nível de alerta (42%). Em uma empresa saudável, nenhum cliente deve ultrapassar 25%.\n\n💡 Diversificar para 6-8 clientes médios reduziria o risco sem impactar receita total.",
  margin: "**Análise de Margem — Histórico**\n\n✅ Margem líquida de 29% está 7pp acima da média do setor (22%).\n\n📈 Tendência: margem subiu de 24% (Out) → 29% (Mar) em 6 meses.\n\n💡 Manter esse ritmo pode chegar a 35%+ em 6 meses com controle de despesas variáveis.",
  burnrate: "**Análise de Burn Rate**\n\n📊 Burn rate atual: $85k/mês. Com caixa disponível de $245k, o runway é de ~87 dias.\n\n⚠️ Ideal mínimo: 180 dias. Você está com metade do recomendado.\n\n💡 Reduzir burn em 10% ($8.5k) já estenderia o runway para ~105 dias.",
  balance: "**Análise de Saldo de Caixa**\n\n📊 O saldo de caixa oscilou entre $218k e $265k nos últimos 6 meses.\n\n⚠️ Queda em Janeiro (pós-festas) é esperada, mas o saldo atual ($245k = 87 dias) está abaixo do ideal de 180 dias.\n\n💡 Meta: atingir $450k em caixa (180 dias) nos próximos 9 meses via crescimento controlado.",
  revgrowth: "**Análise de Crescimento de Receita**\n\n📈 Taxa média de crescimento: +4,4%/mês nos últimos 6 meses.\n\n⚠️ Janeiro teve retração de -8% — tipicamente sazonal. Monitore se se repete em 2026.\n\n✅ Fevereiro recuperou com +14,6%, demonstrando resiliência do negócio.\n\n💡 Meta: manter crescimento acima de 5%/mês para dobrar a receita em 14 meses.",
  fixedvar: "**Análise de Custos Fixos vs Variáveis**\n\n📊 Custos fixos representam 64% das despesas ($54,5k/mês) — dentro do padrão para serviços.\n\n⚠️ Custos variáveis cresceram 60% em 6 meses (Out: $19k → Mar: $30,5k), principalmente marketing.\n\n💡 Revise o ROI das campanhas de marketing. Uma redução de 20% nos variáveis (+$6k/mês) estenderia o runway para ~105 dias.",
  customers: "**Análise da Base de Clientes — Março 2025**\n\n🔴 **Concentração crítica:** Acme Corp representa 42% da receita total ($50,4k/mês). O padrão de segurança é máximo 25% por cliente.\n\n📊 **Distribuição atual:**\n• Acme Corp: 42% — RISCO ALTO (+5% tendência de crescimento)\n• TechStart Ltda: 28% — Moderado (+2%)\n• BuildCo SA: 18% — Em risco (-3% tendência negativa)\n• Outros: 12% — OK\n\n⚠️ **BuildCo SA** apresenta tendência negativa de -3% — monitorar risco de churn.\n\n✅ **Positivo:** Churn zero nos últimos 6 meses. MRR total de $120k estável.\n\n💡 **Ação:** Prospectar 2-3 novos clientes de médio porte para diluir concentração para abaixo de 30% em 6 meses.",
  custtrend: "**Análise de Tendência por Cliente**\n\n📈 **Crescendo:** Acme Corp (+5%) e TechStart (+2%) mostram expansão saudável.\n\n🔴 **Alerta:** BuildCo SA com tendência de -3% nos últimos 3 meses. Verificar satisfação e renovação contratual.\n\n💡 Recomendação: Agendar revisão trimestral com BuildCo para entender o declínio antes que vire churn. Um cliente de $21,6k/mês perdido representaria queda de 18% na receita.",
};
